apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    app: {{ include "frontend-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend-service.name" . }}
    spec:
      containers:
      - name: frontend-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
