apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ronenlmy/frontend-service:1.0
        ports:
        - containerPort: 3000
        env:
          - name: PRODUCTS_SERVICE_URL
            value: "http://products-service:3001"
          - name: ORDERS_SERVICE_URL
            value: "http://orders-service:3002" 

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer