apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: ronenlmy/order-service:1.0
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: "100m"  # Minimum guaranteed CPU
          limits:
            cpu: "500m"  # Maximum allowed CPU

---

apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002